spring.datasource.url=${YP_SP3_DB_URL:jdbc:postgresql://localhost:5432/blog}
spring.datasource.username=${YP_SP3_DB_USER:postgres}
spring.datasource.password=${YP_SP3_DB_PASSWORD:}

post.text.preview-length=128
