spring.datasource.driver-class-name=${YP_SP3_DB_DRIVER:org.h2.Driver}
spring.datasource.url=${YP_SP3_DB_URL:jdbc:h2:mem:blog;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.username=${YP_SP3_DB_USER:sa}
spring.datasource.password=${YP_SP3_DB_PASSWORD:}

post.text.preview-length=128
